# 操作名称
name: 博客部署

# 触发事件
on:
  push:
    branches: master

# 环境变量
env:
  BUILD_ENV: production
  NODE_ENV: production

# 工作流程
jobs:
  build:
    name: 打包代码
    runs-on: ubuntu-latest
    steps:
      - name: 检出项目
        uses: actions/checkout@v2

      - name: 安装依赖并打包
        run: yarn && yarn build

      - name: 上传文件到服务器
        uses: VFiee/sftp-upload-action@v1.3
        with:
          user-name: "root"
          server-ip: "${{secrets.BLOG_SERVER_IP}}"
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
          from-path: "./dist/*"
          to-path: "/var/www/blog"
